### ISSUE TITLE
bug for the testCases NREL-5MW

### ISSUE THREAD

**Issue by jamesliu516** [ImperialCollegeLondon/WInc3D#9]
mpirun -np 16 ../../winc3d NREL-5MW.in
 ===========================================================
 ===========================================================
 ===========================================================
 ======================WInc3D ==============================
 === High fidelity Wind farm simulator =====================
  Developed by G. Deskos : gdeskosv@gmail.com
  Code based on incompact3d
 ===========================================================
 ===========================================================
 ===========================================================
 
 
 
 Fluid flow problem : Constant flow field/wake in a confined domain
 Spatial Resolution: (nx,ny,nz)=( 129, 129, 129)
 Domain dimension  : (lx,ly,lz)=( 252.0, 252.0, 252.0)
 Boundary condition: (nclx,ncly,nclz)=(2,1,1)
 High and low speed: u1= 15.00 and u2= 15.00
 Reynolds number Re:  66667.00000000
 Time step dt      :      0.02000000
 Temporal scheme   : Runge-Kutta 3
 Immersed boundary : off
  
 ++++++++++++++++++++++++++++++++
 Initializing explicit LES Filter
  Classic Smagorinsky is used ... 
  Smagorinsky constant =   0.14000000000000001     
  Filter Size / Grid Size =    1.0000000000000000     
 ++++++++++++++++++++++++++++++++
  
   1.9687500397452398     
 New coef Inter X  0.75000000651925802        5.0000005867332220E-002  -4.6566128730773926E-010
 New coef Inter Y  0.75000000651925802        5.0000005867332220E-002  -4.6566128730773926E-010
 New coef Inter Z  0.75000000651925802        5.0000005867332220E-002  -4.6566128730773926E-010
At line 644 of file acl_elem.f90 (unit = 15, file = 'NRELResources/NRELBlade_N71.al')
Fortran runtime error: End of file
At line 644 of file acl_elem.f90 (unit = 15, file = 'NRELResources/NRELBlade_N71.al')
Fortran runtime error: End of file
At line 644 of file acl_elem.f90 (unit = 15, file = 'NRELResources/NRELBlade_N71.al')
Fortran runtime error: End of file
At line 644 of file acl_elem.f90 (unit = 15, file = 'NRELResources/NRELBlade_N71.al')
Fortran runtime error: End of file
At line 644 of file acl_elem.f90 (unit = 15, file = 'NRELResources/NRELBlade_N71.al')
Fortran runtime error: End of file
At line 644 of file acl_elem.f90 (unit = 15, file = 'NRELResources/NRELBlade_N71.al')
Fortran runtime error: End of file
--------------------------------------------------------------------------
mpirun has exited due to process rank 1 with PID 6378 on
node liu-Precision-Tower-7910 exiting improperly. There are two reasons this could occur:

1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.

2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"

This may have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).

**Comment by gdeskos** [comment]
This is NOT a bug, please make sure you use the correct paths to the input *.in OR *.turb OR *.al files.

**Comment by ArturoMS13** [comment]
Dear  jamesliu516,

you need to generate the input files for the blade.
To do so, go to the "NRELResources" folder and run "python InterpolateNRELBlade 71 51"  before running winc3d.

Please, come back to us with the outcome.
Best regards

**Comment by jamesliu516** [comment]
Thank you very much. The code can be run now.  @ArturoMS13

**Comment by ArturoMS13** [comment]
Nice, thank you.
